### ISSUE TITLE
XEP-0363: HTTP File Upload

### ISSUE THREAD

**Issue by LogicParrot** [kontalk/specs#12]
[Conversations](https://github.com/siacs/Conversations) uses it and it works great.

- Asynchronous, receiving client doesn't need to be online.
- Works even if the receiving side does not support it.

**Comment by LogicParrot** [comment]
Xep link: http://xmpp.org/extensions/xep-0363.html

**Comment by daniele-athome** [comment]
Thanks for suggesting, we were looking into implementing that. Issue tracking can be found in the server repository, although I'll keep this to track modifications to the spec files.

**Comment by abika** [comment]
I'll add a Smack extension to client-common. We can already add support for incoming messages and move the upload part at a later time.

**Comment by daniele-athome** [comment]
@abika what do you mean? Incoming messages will be using out-of-band data, only the upload part (read: the URL to upload to) will change. Or maybe I'm not getting your point?

**Comment by abika** [comment]
omg, yes. XEP-363 is only about the upload part, missed that.

In Conversations the link transfer from client-to-client is simply done by sending it inside the body:
```
...
<body>https://jabber.de:5281/upload/b818b5f5-8da4-41b4-9285-92e27a123456/IMG_20160119_1234.jpg</body>
...
```
And the OOB-Data extension is not supported (but it won't work with Kontalk's upload service, anyway).

**Comment by daniele-athome** [comment]
Why not including both? (URL in the body - for incompatible clients - and OOB - for clients who can understand what is going on). I will do the same in the Android client.

**Comment by abika** [comment]
yes, once the download doesn't require authorization anymore. Otherwise the user can't open then link anyway.

**Comment by daniele-athome** [comment]
> yes, once the download doesn't require authorization anymore. Otherwise the (non-Kontalk) user can't open then link anyway.

Exactly.

**Comment by iNPUTmice** [comment]
> Why not include both? (URL in the body - for incompatible clients - and OOB - for clients who can understand what is going on). I will do the same in the Android client.

Conversations does exactly this. oob and body (for non encrypted messages that is)
