### ISSUE TITLE
Add german wikipedia article to "talking about us"

### ISSUE THREAD

**Issue by webratte** [kontalk/specs#14]
https://de.wikipedia.org/wiki/Kontalk

**Comment by webratte** [comment]
You can drop http://de.pluspedia.org/wiki/Kontalk
That's only a side for articles who not will accepted in Wikipedia.
And it's not really up to date ;-)

**Comment by daniele-athome** [comment]
Fixed in https://github.com/kontalk/specs/wiki/Talking-about-us/4f2380756af256b9cfa90528883107432a67c1dc
Thanks!
