### ISSUE TITLE
Kontalk's forum website

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/specs#15]
When I'm trying to go to the forum I get the following error:
<code>
An error occurred during a connection to forum.kontalk.org. OCSP response has an invalid signature. (Error code: sec_error_ocsp_bad_signature)
<code>

**Comment by daniele-athome** [comment]
What browser and version are you using?

**Comment by daniele-athome** [comment]
> I'm using IceCatMobile 38.8.0 but now as you mentioned it doesn't seem to be up to date but still latest built in F-Droid. I'll look for another browser. I've tried Orfox 45.5.1 esr but it doesn't show anything.

I believe you mistakenly posted your answer for this issue over to the other repository.

What about desktop browsers? Do you get the same error?

**Comment by OffifialMITX** [comment]
Oh, yes, sorry for that.
I've tried with Firefox ESR 45.4.0 on desktop again and it works fine now.
