### ISSUE TITLE
Encryption XEP

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/specs#5]
- [ ] reference to old XEP-0027
- [ ] client discovery
- [ ] suggest key publishing through XEP-0189
- [ ] Message/CPIM enforcement
- [ ] standard OpenPGP encryption+signing
- [ ] use e2e or openpgp namespace?
- [ ] security considerations

**Comment by LogicParrot** [comment]
Just want to bring [OMEMO](https://conversations.im/omemo/) to your attention in case you're unaware of it. It is still a [ProtoXep](https://conversations.im/xeps/multi-end.html), and is the xmpp version of the well known [TextSecure Axolotl protocol](https://github.com/WhisperSystems/Signal-Android/wiki/ProtocolV2). [Conversations](https://github.com/siacs/Conversations) is currently the only client deploying it, and it works well.

**Comment by LogicParrot** [comment]
It has several advantages over OpenPGP, including convenient multi-device support (no need to transfer keys) and deniability.

**Comment by daniele-athome** [comment]
Thank you, we know about OMEMO, but we forgot to update this issue :-) we'll probably take that road too.

**Comment by daniele-athome** [comment]
We will soon switch to [XEP-0374](http://xmpp.org/extensions/xep-0374.html).Closing.
