### ISSUE TITLE
Too many "secure" messaging but require a server: What about Tox?

### ISSUE THREAD

**Issue by timofonic** [kontalk/specs#9]
Hello.

There's to many projects promising secure messaging, yet they require a server.

What about Tox?

https://github.com/irungentoo/toxcore

Why not merging efforts and joining the best approachs? This segmentation is killing to have reliable and secure FOSS messaging plus other approaches (teamgroups, file sharing...).

Kind regards.

**Comment by daniele-athome** [comment]
Hi, I'm sorry but Kontalk was born with another approach in mind. Tox is p2p, IMHO the mobile world is not ready for pure p2p: too many obstacles, starting from security and energy requirements plus other things I won't get into now. Assistance from server will still be needed for many years to come.
